---
title: "RawFiles"
author: "Murilo Junqueira"
date: "28/02/2020"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| RawFile_ProjetctFileName                              | FileList_FilePath                                                                      | RawFile_Source | RawFile_AutoDownload | RawFile_GitHub | RawFile_Size | RawFile_Date         | RawFile_URL                                                                                                       | RawFile_URLBackup                                                                                                 | RawFile_Comments                                                                                                                                                                                                                                                                                                                           | 
|-------------------------------------------------------|----------------------------------------------------------------------------------------|----------------|----------------------|----------------|--------------|----------------------|-------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------| 
| 05112017_PB CENSUS 2016.xlsx                          | data/raw/PBCENSUS Spada/05112017_PB CENSUS 2016.xlsx                                   | Spada (2012)   | 0                    | 0              | 411102       | 2018-02-20 15:41:58Z |                                                                                                                   |                                                                                                                   | Nós temos uma versão atualizada do banco com os dados de 2016. Existe uma versão pública do banco do dataverse que vai até 2012: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EDSNJS                                                                                                                           | 
| Finbra89-93.zip                                       | data/raw/Finbra/OriginalFiles/Finbra89-93.zip                                          | STN            | 1                    | 0              | 5743101      | 2019-08-17 23:31:37Z | http://www.tesouro.fazenda.gov.br/documents/10180/137007/Finbra89-93.zip/de9140b6-b5bc-4777-983e-7246d63a97e9     | https://dl.dropboxusercontent.com/s/m8w0qcgopmkzqfc/Finbra89-93.zip                                               | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra94-96.zip                                       | data/raw/Finbra/OriginalFiles/Finbra94-96.zip                                          | STN            | 1                    | 0              | 5041144      | 2019-08-17 23:52:00Z | http://www.tesouro.fazenda.gov.br/documents/10180/137007/Finbra94-96.zip/fc1c7c2a-b024-4848-8ffc-bf619c40272b     | https://dl.dropboxusercontent.com/s/8zkld5oc9y2gyz3/Finbra94-96.zip                                               | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra1997.zip                                        | data/raw/Finbra/OriginalFiles/Finbra1997.zip                                           | STN            | 1                    | 0              | 1711771      | 2019-08-29 22:07:26Z | http://www.tesouro.fazenda.gov.br/documents/10180/137007/Finbra1997.zip/5d6360b7-a634-4504-825f-a44ebf83c45a      | https://dl.dropboxusercontent.com/s/wuaht8ffwqbtvm3/Finbra1997.zip                                                | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra1998.zip                                        | data/raw/Finbra/OriginalFiles/Finbra1998.zip                                           | STN            | 1                    | 0              | 2870995      | 2019-08-29 22:07:30Z | http://www.tesouro.fazenda.gov.br/documents/10180/137007/Finbra1998.zip/713fb0ae-bfe3-4750-bbae-48a3f50c8f61      | https://dl.dropboxusercontent.com/s/za9eqittyx0uh8t/Finbra1998.zip                                                | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra1999.zip                                        | data/raw/Finbra/OriginalFiles/Finbra1999.zip                                           | STN            | 1                    | 0              | 2864484      | 2019-08-29 22:07:32Z | http://www.tesouro.fazenda.gov.br/documents/10180/137007/Finbra1999.zip/abc3629d-fd95-4cb4-b35e-733aacbf3217      | https://dl.dropboxusercontent.com/s/4mlzsayls3tu2jt/Finbra1999.zip                                                | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra2000.zip                                        | data/raw/Finbra/OriginalFiles/Finbra2000.zip                                           | STN            | 1                    | 0              | 3419669      | 2019-08-29 22:07:34Z | http://www.tesouro.fazenda.gov.br/documents/10180/137007/Finbra2000.zip/312ba81c-4ea7-45b8-af1e-97c1eccc0599      | https://dl.dropboxusercontent.com/s/ztngcfzt6gu85mx/Finbra2000.zip                                                | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra2001v0809.zip                                   | data/raw/Finbra/OriginalFiles/Finbra2001v0809.zip                                      | STN            | 1                    | 0              | 3516592      | 2019-08-29 22:07:36Z | http://www.tesouro.fazenda.gov.br/documents/10180/137713/Finbra2001v0809.zip                                      | https://dl.dropboxusercontent.com/s/uscpahl4oc7mnti/Finbra2001v0809.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra2002v0809.zip                                   | data/raw/Finbra/OriginalFiles/Finbra2002v0809.zip                                      | STN            | 1                    | 0              | 4299904      | 2019-08-29 22:07:38Z | http://www.tesouro.fazenda.gov.br/documents/10180/137713/Finbra2002v0809.zip                                      | https://dl.dropboxusercontent.com/s/nciadofccyflmb5/Finbra2002v0809.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra2003.zip                                        | data/raw/Finbra/OriginalFiles/Finbra2003.zip                                           | STN            | 1                    | 0              | 4553840      | 2019-08-29 22:07:40Z | http://www.tesouro.fazenda.gov.br/documents/10180/137007/Finbra2003.zip                                           | https://dl.dropboxusercontent.com/s/cez8hd3t699pjez/Finbra2003.zip                                                | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra2004v0809b.zip                                  | data/raw/Finbra/OriginalFiles/Finbra2004v0809b.zip                                     | STN            | 1                    | 0              | 5482863      | 2019-08-29 22:07:44Z | http://www.tesouro.fazenda.gov.br/documents/10180/137713/Finbra2004v0809b.zip                                     | https://dl.dropboxusercontent.com/s/nrwq2jqqr4cm1ly/Finbra2004v0809b.zip                                          | .                                                                                                                                                                                                                                                                                                                                          | 
| Finbra2005v0809.zip                                   | data/raw/Finbra/OriginalFiles/Finbra2005v0809.zip                                      | STN            | 1                    | 0              | 5784608      | 2019-08-29 22:07:47Z | http://www.tesouro.fazenda.gov.br/documents/10180/137713/Finbra2005v0809.zip                                      | https://dl.dropboxusercontent.com/s/938hrr8r0eab4md/Finbra2005v0809.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| pge_finbra_2006.zip                                   | data/raw/Finbra/OriginalFiles/pge_finbra_2006.zip                                      | STN            | 1                    | 0              | 6077208      | 2019-08-29 22:07:49Z | http://www.tesouro.fazenda.gov.br/documents/10180/327844/pge_finbra_2006.zip/21e3e641-502e-4639-951d-608874507e01 | https://dl.dropboxusercontent.com/s/3uymgtk31ucjdrt/pge_finbra_2006.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| pge_finbra_2007.zip                                   | data/raw/Finbra/OriginalFiles/pge_finbra_2007.zip                                      | STN            | 1                    | 0              | 6333739      | 2019-08-29 22:07:52Z | http://www.tesouro.fazenda.gov.br/documents/10180/327844/pge_finbra_2007.zip/61957017-14f5-450b-9155-833dd3fb14df | https://dl.dropboxusercontent.com/s/79uajvh4ctxopze/pge_finbra_2007.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| pge_finbra_2008.zip                                   | data/raw/Finbra/OriginalFiles/pge_finbra_2008.zip                                      | STN            | 1                    | 0              | 6348738      | 2019-08-29 22:07:54Z | http://www.tesouro.fazenda.gov.br/documents/10180/327844/pge_finbra_2008.zip/91ba191d-ee56-4a9e-9064-9c9583d4c67d | https://dl.dropboxusercontent.com/s/86r9zd25yajkuij/pge_finbra_2008.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| pge_finbra_2009.zip                                   | data/raw/Finbra/OriginalFiles/pge_finbra_2009.zip                                      | STN            | 1                    | 0              | 11027385     | 2019-08-29 22:07:57Z | http://www.tesouro.fazenda.gov.br/documents/10180/327844/pge_finbra_2009.zip/8f85ed32-7a52-47dc-a7ba-e5ecaa551899 | https://dl.dropboxusercontent.com/s/0euw3m80fk3yfk6/pge_finbra_2009.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| pge_finbra_2010.zip                                   | data/raw/Finbra/OriginalFiles/pge_finbra_2010.zip                                      | STN            | 1                    | 0              | 11172080     | 2019-08-29 22:08:00Z | http://www.tesouro.fazenda.gov.br/documents/10180/327844/pge_finbra_2010.zip/4560c066-10a1-483c-9067-7f1bb60b4152 | https://dl.dropboxusercontent.com/s/u1vaww48yfxb2ki/pge_finbra_2010.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| pge_finbra_2011.zip                                   | data/raw/Finbra/OriginalFiles/pge_finbra_2011.zip                                      | STN            | 1                    | 0              | 11162086     | 2019-08-29 22:08:04Z | http://www.tesouro.fazenda.gov.br/documents/10180/327844/pge_finbra_2011.zip/07279645-05d4-4835-9d59-b931f7144b0c | https://dl.dropboxusercontent.com/s/spzc3jgmt01vj8k/pge_finbra_2011.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| pge_finbra_2012.zip                                   | data/raw/Finbra/OriginalFiles/pge_finbra_2012.zip                                      | STN            | 1                    | 0              | 10996653     | 2019-08-29 22:08:07Z | http://www.tesouro.fazenda.gov.br/documents/10180/327844/pge_finbra_2012.zip/561d62f0-caa9-4fe2-b901-911f7e41b8d8 | https://dl.dropboxusercontent.com/s/spzc3jgmt01vj8k/pge_finbra_2011.zip                                           | .                                                                                                                                                                                                                                                                                                                                          | 
| finbra_MUN_ReceitasOrcamentarias(AnexoI-C) - 2013.zip | data/raw/Finbra/OriginalFiles/finbra_MUN_ReceitasOrcamentarias(AnexoI-C) - 2013.zip    | STN            | 0                    | 0              | 4892850      | 2019-12-14 21:21:01Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/g0uast0nmj89ebe/finbra_MUN_ReceitasOrcamentarias%28AnexoI-C%29%20-%202013.zip | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_ReceitasOrcamentarias(AnexoI-C) - 2014.zip | data/raw/Finbra/OriginalFiles/finbra_MUN_ReceitasOrcamentarias(AnexoI-C) - 2014.zip    | STN            | 0                    | 0              | 5039782      | 2019-12-14 21:24:40Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/cwr74ekb5vyiqbq/finbra_MUN_ReceitasOrcamentarias%28AnexoI-C%29%20-%202014.zip | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_ReceitasOrcamentarias(AnexoI-C) - 2015.zip | data/raw/Finbra/OriginalFiles/finbra_MUN_ReceitasOrcamentarias(AnexoI-C) - 2015.zip    | STN            | 0                    | 0              | 5883036      | 2019-12-14 21:30:51Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/jr3s6w8ck6agyrj/finbra_MUN_ReceitasOrcamentarias%28AnexoI-C%29%20-%202015.zip | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_ReceitasOrcamentarias(AnexoI-C) - 2016.zip | data/raw/Finbra/OriginalFiles/finbra_MUN_ReceitasOrcamentarias(AnexoI-C) - 2016.zip    | STN            | 0                    | 0              | 6253996      | 2019-12-14 21:45:00Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/pkboqchwovnd3wr/finbra_MUN_ReceitasOrcamentarias%28AnexoI-C%29%20-%202016.zip | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_DespesasOrcamentarias(AnexoI-D) - 2013.zip | data/raw/Finbra/OriginalFiles/finbra_MUN_DespesasOrcamentarias(AnexoI-D) - 2013.zip    | STN            | 0                    | 0              | 7082741      | 2019-12-14 21:19:45Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/2f1et1n50xf96u8/finbra_MUN_DespesasOrcamentarias%28AnexoI-D%29%20-%202013.zip | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_DespesasOrcamentarias(AnexoI-D) - 2014.zip | data/raw/Finbra/OriginalFiles/finbra_MUN_DespesasOrcamentarias(AnexoI-D) - 2014.zip    | STN            | 0                    | 0              | 7159921      | 2019-12-14 21:25:04Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/2f1et1n50xf96u8/finbra_MUN_DespesasOrcamentarias%28AnexoI-D%29%20-%202013.zip | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_DespesasOrcamentarias(AnexoI-D) - 2015.zip | data/raw/Finbra/OriginalFiles/finbra_MUN_DespesasOrcamentarias(AnexoI-D) - 2015.zip    | STN            | 0                    | 0              | 7580462      | 2019-12-14 21:33:50Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/kgijjqy8yracx5n/finbra_MUN_DespesasOrcamentarias%28AnexoI-D%29%20-%202015.zip | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_DespesasOrcamentarias(AnexoI-D) - 2016.zip | data/raw/Finbra/OriginalFiles/finbra_MUN_DespesasOrcamentarias(AnexoI-D) - 2016.zip    | STN            | 0                    | 0              | 7106066      | 2019-12-14 21:44:41Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/13cdrkt4bs9zgv8/finbra_MUN_DespesasOrcamentarias%28AnexoI-D%29%20-%202016.zip | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_DespesasporFuncao(AnexoI-E) - 2013.zip     | data/raw/Finbra/OriginalFiles/finbra_MUN_DespesasporFuncao(AnexoI-E) - 2013.zip        | STN            | 0                    | 0              | 8388564      | 2019-12-14 21:26:07Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/g8q13gp8ocuehoi/finbra_MUN_DespesasporFuncao%28AnexoI-E%29%20-%202013.zip     | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_DespesasporFuncao(AnexoI-E) - 2014.zip     | data/raw/Finbra/OriginalFiles/finbra_MUN_DespesasporFuncao(AnexoI-E) - 2014.zip        | STN            | 0                    | 0              | 8371863      | 2019-12-14 21:33:56Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/z6k7leevq8j8utb/finbra_MUN_DespesasporFuncao%28AnexoI-E%29%20-%202014.zip     | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_DespesasporFuncao(AnexoI-E) - 2015.zip     | data/raw/Finbra/OriginalFiles/finbra_MUN_DespesasporFuncao(AnexoI-E) - 2015.zip        | STN            | 0                    | 0              | 8787491      | 2019-12-14 21:42:34Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/z6k7leevq8j8utb/finbra_MUN_DespesasporFuncao%28AnexoI-E%29%20-%202014.zip     | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| finbra_MUN_DespesasporFuncao(AnexoI-E) - 2016.zip     | data/raw/Finbra/OriginalFiles/finbra_MUN_DespesasporFuncao(AnexoI-E) - 2016.zip        | STN            | 0                    | 0              | 8165235      | 2019-12-14 21:53:03Z | https://siconfi.tesouro.gov.br/siconfi/pages/public/consulta_finbra/finbra_list.jsf                               | https://dl.dropboxusercontent.com/s/g1yz59y7tw30udu/finbra_MUN_DespesasporFuncao%28AnexoI-E%29%20-%202016.zip     | Download captcha                                                                                                                                                                                                                                                                                                                           | 
| DeParaFinbra.csv                                      | data/dataset/DeParaFinbra.csv                                                          | Own Research   | 1                    | 1              | 13609        | 2019-12-14 21:47:43Z |                                                                                                                   |                                                                                                                   |                                                                                                                                                                                                                                                                                                                                            | 
| DeParaUGCodIBGE.csv                                   | data/dataset/DeParaUGCodIBGE.csv                                                       | Own Research   | 1                    | 1              | 217006       | 2018-05-28 12:59:10Z |                                                                                                                   |                                                                                                                   |                                                                                                                                                                                                                                                                                                                                            | 
| Municipios.csv                                        | data/dataset/Municipios.csv                                                            | Own Research   | 1                    | 1              | 175902       | 2018-05-27 12:05:59Z |                                                                                                                   |                                                                                                                   |                                                                                                                                                                                                                                                                                                                                            | 
| ContasPublicas.csv                                    | data/dataset/ContasPublicas.csv                                                        | Own Research   | 1                    | 1              | 827          | 2019-09-17 08:08:00Z |                                                                                                                   |                                                                                                                   |                                                                                                                                                                                                                                                                                                                                            | 
| UEToCodIBGE.csv                                       | data/dataset/UEToCodIBGE.csv                                                           | Own Research   | 1                    | 1              | 82967        | 2018-03-02 16:25:50Z |                                                                                                                   |                                                                                                                   |                                                                                                                                                                                                                                                                                                                                            | 
| votacao_candidato_munzona_2000.zip                    | data/raw/TSE/2000/votacao_candidato_munzona_2000.zip                                   | TSE            | 1                    | 0              | 17502789     | 2019-10-28 00:00:09Z | http://agencia.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_2000.zip    |                                                                                                                   |                                                                                                                                                                                                                                                                                                                                            | 
| TSE-relacao-candidatos-1996.zip                       | data/raw/TSE/TSE-relacao-candidatos-1996/TSE-relacao-candidatos-1996.zip               | TSE            | 1                    | 0              | 15738329     | 2019-10-27 21:25:48Z | http://www.justicaeleitoral.jus.br/arquivos/candidatos-1996                                                       |                                                                                                                   | "A página onde encontrei o link é a http://www.tse.jus.br/eleicoes/eleicoes-anteriores/eleicoes-1996/divulgacao-candidatos-1996. Attention: Extract file ""data/raw/TSE/TSE-relacao-candidatos-1996/TSE-relacao-candidatos-1996.zip""  and then export all data to file ""data/raw/TSE/TSE-relacao-candidatos-1996/Candidatos_1996.xlsx""" | 
| Resultado_da_Eleição_(Por_Municipio)_1996.csv         | data/raw/TSE/TSE-relacao-candidatos-1996/Resultado_da_Eleição_(Por_Municipio)_1996.csv | TSE            | 0                    | 1              | 7628         | 2019-10-27 22:11:06Z | http://www.tse.jus.br/eleicoes/eleicoes-anteriores/eleicoes-1996/resultados-das-eleicoes                          |                                                                                                                   | Esse link não é de download automático. A página indicada te leva a uma tele de seleção, onde se deve selecionar os filtros. Deve escolher todas as UF, todos os municípios, todas as situações eleitorais, todos os partidos, cargo de prefeito e turno 2.                                                                                | 
| DeParaSitEleitoral.csv                                | data/dataset/DeParaSitEleitoral.csv                                                    | Own Research   | 1                    | 1              | 2337         | 2019-12-01 17:57:14Z |                                                                                                                   |                                                                                                                   |                                                                                                                                                                                                                                                                                                                                            | 
